@startuml Acceso y Perfiles

!include Actores.puml

package "Acceso y Perfiles"{
    usecase CU_PG_001 as "Iniciar Sesión"
    usecase CU_PG_002 as "Crear Cuenta"
    usecase CU_PG_003 as "Gestionar Datos Personales"

    Usuario --> CU_PG_001
    Usuario --> CU_PG_003
    Interesado --> CU_PG_002

}


@enduml