@startuml Administración de Usuarios

!include Actores.puml

package "Administración de Usuarios" {
    usecase CU_MU_001 as "Consultar Usuarios"
    usecase CU_MU_002 as "Validar documentación"
}

Coordinacion --> CU_MU_001
Coordinacion --> CU_MU_002

@enduml
