@startuml Gestión de Eventos

!include Actores.puml

package "Gestión de Eventos" {

    ' CRUD de eventos
    usecase CU_GE_001 as "
    CU_GE_001
    ---
    Crear Evento
    "
    usecase CU_GE_002 as "
    CU_GE_002
    ---
    Consultar Eventos
    "
    usecase CU_GE_003 as "
    CU_GE_003
    ---
    Modificar Evento
    "
    usecase CU_GE_004 as "
    CU_GE_004
    ---
    Eliminar Evento
    "
    
    ' Gestión de inscripciones y pagos
    usecase CU_GE_007 as "
    CU_GE_007
    ---
    Aprobar-Gestionar Solicitudes de Inscripción
    "
    usecase CU_GE_008 as "
    CU_GE_008
    ---
    Validar Pagos Manuales
    "
    
    ' Generación de documentos
    usecase CU_GE_005 as "
    CU_GE_005
    ---
    Generar Constancias
    "
    usecase CU_GE_006 as "
    CU_GE_006
    ---
    Generar Reportes de Eventos
    "
}

' CRUD de eventos
coordinadora_ec --> CU_GE_001
Coordinacion --> CU_GE_002
coordinadora_ec --> CU_GE_003
coordinadora_ec --> CU_GE_004

' Gestión operativa
Coordinacion --> CU_GE_007
Coordinacion --> CU_GE_008

' Documentación
coordinadora_ec --> CU_GE_005
Coordinacion --> CU_GE_006

' Flujo lógico
CU_GE_001 ..> CU_GE_002 : alimenta
CU_GE_007 ..> CU_GE_008 : precede
CU_GE_008 ..> CU_GE_005 : habilita

@enduml