@startuml Gestión de Leads

!include Actores.puml

package "Gestión de leads" as gestion_leads {
    ' Captura de leads
    usecase CU_VE_001 as "
    CU_VE_001
    ---
    Recuperar leads de fuentes externas"
    usecase CU_VE_002 as "
    CU_VE_002
    ---
    Agregar lead manualmente"
    
    ' Gestión de leads
    usecase CU_VE_003 as "
    CU_VE_003
    ---
    Visualizar leads"
    usecase CU_VE_004 as "
    CU_VE_004
    ---
    Asignar leads"
    
    ' Conversión
    usecase CU_VE_005 as "
    CU_VE_005
    ---
    Convertir lead en oportunidad"
}

' Captura automática
gestion_leads --> CU_VE_001
CU_VE_001  <--  MetaAds

' Gestión manual
equipo_ventas --> CU_VE_002
Staff --> CU_VE_003
responsable_ventas --> CU_VE_004

' Conversión
equipo_ventas --> CU_VE_005

' Flujo lógico
CU_VE_001 ..> CU_VE_003 : alimenta
CU_VE_002 ..> CU_VE_003 : alimenta
CU_VE_003 ..> CU_VE_004 : precede
CU_VE_004 ..> CU_VE_005 : precede

@enduml