@startuml Gestión de Oportunidades

!include Actores.puml

package "Gestión de Oportunidades" {
    ' Interacción principal
    usecase CU_VE_006 as "Registrar Interacción con Oportunidad"
    
    ' Seguimiento y tareas
    usecase CU_VE_007 as "Agendar Tarea de Seguimiento"
    usecase CU_VE_009 as "Consultar recordatorios"
    usecase CU_VE_010 as "Gestionar Notificación de Recordatorio"
    
    ' Cierre y gestión documental
    usecase CU_VE_008 as "Cerrar Oportunidad Ganada-Perdida"
    usecase CU_VE_011 as "Cargar Documentación en Nombre del Cliente"
    usecase CU_VE_012 as "Consultar estado del pago"
}

' Interacciones principales
promotor_ventas --> CU_VE_006
promotor_ventas --> CU_VE_011
promotor_ventas --> CU_VE_012
promotor_ventas --> CU_VE_009
promotor_ventas --> CU_VE_010

' Consultas de coordinación
Coordinacion --> CU_VE_012

' Notificaciones del sistema
CU_VE_010 <-- "Gestión de Oportunidades" 

' Relaciones de extensión y dependencia
CU_VE_007 .> CU_VE_006 : extiende
CU_VE_008 .> CU_VE_006 : extiende
CU_VE_007 ..> CU_VE_009 : genera
CU_VE_009 ..> CU_VE_010 : activa

@enduml