@startuml Módulo de Usuarios

!include Actores.puml

package "Módulo de Usuarios" {
    usecase CU_MU_001 as "Consultar Usuarios"
    usecase CU_MU_002 as "Validar documentación"
    usecase CU_MU_003 as "Registrar Capacitador"
    usecase CU_MU_004 as "Consultar Capacitadores"
    usecase CU_MU_005 as "Modificar Información de Capacitador"
    usecase CU_MU_006 as "Archivar-Eliminar Capacitador"
    usecase CU_MU_007 as "Registrar-Actualizar Información de Pago-Facturación de Capacitador"
    usecase CU_MU_008 as "Validar Información de Pago-Facturación Propia"
    usecase CU_MU_009 as "Consultar Capacitaciones Asignadas"
}

Capacitador --> CU_MU_009
Coordinacion --> CU_MU_001
Coordinacion --> CU_MU_002
Coordinacion --> CU_MU_004
coordinadora_ec --> CU_MU_005
coordinadora_ec --> CU_MU_006
coordinadora_ec --> CU_MU_007
coordinadora_ec --> CU_MU_003
Capacitador --> CU_MU_008

@enduml