@startuml Público General

!include Actores.puml

package "Público General" {
    ' Flujo principal de inscripción
    usecase CU_PG_004 as "
    CU_PG_004
    ---
    Solicitar Inscripción a Evento
    "
    usecase CU_PG_006 as "
    CU_PG_006
    ---
    Cargar Documentos (por el usuario)
    "
    usecase CU_PG_007 as "
    CU_PG_007
    ---
    Consultar Estado de mis Solicitudes-Inscripciones
    "
    usecase CU_PG_008 as "
    CU_PG_008
    ---
    Volver a Enviar Solicitud
    "
    usecase CU_PG_005 as "
    CU_PG_005
    ---
    Realizar Pago de Solicitud Aprobada
    "
    
    ' Gestión post-inscripción
    usecase CU_PG_009 as "
    CU_PG_009
    ---
    Consultar Mis Eventos
    "
}

' Flujo de inscripción
Interesado --> CU_PG_004
Interesado --> CU_PG_006
Interesado --> CU_PG_007
Interesado --> CU_PG_008
Interesado --> CU_PG_005

' Post-inscripción
Participante --> CU_PG_009

' Relaciones de flujo
CU_PG_004 ..> CU_PG_006 : incluye
CU_PG_007 ..> CU_PG_008 : extiende
CU_PG_004 ..> CU_PG_005 : precede

@enduml