@startuml Use Case System

title Diagrama de casos de uso del sistema

!include Actores.puml
!include Acceso y Perfiles.puml
!include Público General.puml
!include Gestión de Leads.puml
!include Gestión de Oportunidades.puml
!include Gestión de Categorías.puml
!include Gestión de Eventos.puml
!include Gestión de Capacitadores.puml
!include Administración de Usuarios.puml


@enduml
